### ISSUE TITLE
PR #27 causes issues with RFV

### ISSUE THREAD

**Issue by cybertelx** [SnowbankDAO/snowbank-frontend#28]
**Describe the bug**
The RFV shown on the dashboard is -$0.00.

**To Reproduce**
1. Go on the Netlify preview URL for #27 or the current production app URL
2. Enter dashboard
3. See an impossibly low RFV

**Expected behavior**
The actual RFV should be displayed.

**Workarounds (if any)**
Use a preview URL for a PR before #27.

**Screenshots**

**Desktop (please complete the following information):**
Irrelevant, it affects all users

**Smartphone (please complete the following information):**
Irrelevant, it affects all users

**Additional context**
Educated guess as I'm not on my computer, but I believe it may be caused by the new MIM-AVAX turbine being added without updating the RFV calculation logic

**Comment by 0xOtoguro** [comment]
Thanks for the issue! fixed by #29
