### ISSUE TITLE
Weird behaviour with Snowglobe sidebar

### ISSUE THREAD

**Issue by cgomez9** [SnowbankDAO/snowbank-frontend#6]
**Describe the bug**
When you go into Snowglobe section, the right sidebar appears and disappears in an infinite loop.

**To Reproduce**
Go into Snowglobe section

**Expected behavior**
The sidebar should appear if need it and if not should be hidden.

**Screenshots**
https://streamable.com/fx3xvw

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: 96.0.4664.55

**Additional context**
Keep the awesome work guys, let me know if I can help solve this small bug!

**Comment by skeeter6380** [comment]
seems like a quick fix is to `overflow: hidden` on the `.snowglobe-card`.  I'll submit a PR.

**Comment by 0xOtoguro** [comment]
This has been fixed by #12
